# -*- coding: utf-8 -*-
"""Khanal Foods Pre-Analytics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uNW7olXresTkbKm2RG0emYI3uv9nnCAj

# Khanal Foods Analytics Dashboard

#ToDo :

- Sales Data
- Return Data

All aggregation for single items
"""

# pip install pandas

# from google.colab import drive
# drive.mount('/content/drive')

# import pandas as pd

# # Replace 'file_path.xlsx' with the actual path to your Excel file
# df      = pd.read_excel('Invoice Details.xlsx')
# item_df = pd.read_excel('Items Export.xlsx')
# bp_df   = pd.read_excel('List of Business Partners.xlsx')
# df.head()

# # Assuming item_df is your DataFrame
# columns_to_keep = ["Item No.", "Item Description", "Brand Name", "Product Stage", "Product Category", "Product Sub-Category"]

# # Create a new DataFrame with only the desired columns
# item_df = item_df[columns_to_keep]
# item_df.head()

# bp_df.head()

# common_column = "Item No."

# # Define the columns you want to add to df from item_df
# columns_to_add = ["Brand Name", "Product Stage", "Product Category", "Product Sub-Category"]

# # Merge the DataFrames based on the common column
# df = df.merge(item_df[[common_column] + columns_to_add], on=common_column, how="left")
# df.head()

# bp_df.rename(columns={'BP Code': "Customer/Vendor Code"}, inplace=True)
# bp_df.head()

# # Define the common column names
# common_column = "Customer/Vendor Code"

# # Define the column you want to add to df from bp_df
# column_to_add = "Group Code"

# # Merge the DataFrames based on the common column
# df = df.merge(bp_df[[common_column, column_to_add]], left_on=common_column, right_on=common_column, how="left")

# df.head()
import pandas as pd
csv_file_path = 'MasterDF.csv'
# /home/frappe/frappe-bench/apps/khanal_tech_integrations/khanal_tech_integrations/utils
df = pd.read_csv('/workspace/development/ape-bench/apps/khanal_tech_integrations/khanal_tech_integrations/utils/test_api_folder/Master_DF.csv')

# # Export the DataFrame to a CSV file
# df.to_csv(csv_file_path, index=False)

# Assuming df is your DataFrame with the "Item No." column
unique_item_count = df['Item No.'].nunique()

# Print the number of unique "Item No." values
print("Number of unique Item Nos:", unique_item_count)

# Filter rows where "Item No." starts with "PM"
filtered_df = df[df['Item No.'].str.startswith('PM')]

# Display or work with the filtered DataFrame
filtered_df.head()

def format_row_total(x):
    return f'{x:.2f}'  # Format as a float with 2 decimal places

result_df = df.groupby(['Item No.'])[['Quantity', 'Row Total']].sum().reset_index()
result_df = result_df.merge(df[['Item No.', 'Item/Service Description']].drop_duplicates(), on='Item No.', how='left')
result_df = result_df[['Item No.', 'Item/Service Description', 'Quantity', 'Row Total']]
result_sorted = result_df.sort_values(by='Row Total', ascending=False)
result_sorted['Row Total'] = result_sorted['Row Total'].apply(format_row_total)

csv_file_path = 'sorted_data.csv'

# Export the DataFrame to a CSV file
result_sorted.to_csv(csv_file_path, index=False)

result_sorted.head()

import datetime
def which_week(date_time):
  return date_time.isocalendar()[1]

df['Posting Date'] = pd.to_datetime(df['Posting Date'], format='%d/%b/%Y')
df['Month']       = df['Posting Date'].dt.month
df['Year']        = df['Posting Date'].dt.year
df['Week']        = df['Posting Date'].apply(which_week)


df.head()

result_df = df.groupby(['Month', 'Year', 'Item No.'])[['Quantity', 'Row Total']].sum().reset_index()
# Merge with the original DataFrame to get the "Item/Service Description" column
result_df = result_df.merge(df[['Item No.', 'Item/Service Description']].drop_duplicates(), on='Item No.', how='left')

# Reorder the columns as per your requirement
result_df = result_df[['Item No.', 'Item/Service Description', 'Quantity', 'Row Total', 'Month', 'Year']]

# csv_file_path = 'MoM.csv'

# # Export the DataFrame to a CSV file
# result_df.to_csv(csv_file_path, index=False)
result_df.head()

# Pivot the DataFrame to create columns for each month-year combination
pivoted_df = result_df.pivot_table(index=["Item No.", "Item/Service Description"],
                                   columns=["Month", "Year"],
                                   values=["Quantity", "Row Total"],
                                   aggfunc="sum", fill_value=0)

# Flatten the column multi-index by joining levels and resetting index
pivoted_df.columns = [' '.join(map(str, col)) for col in pivoted_df.columns.values]
pivoted_df.reset_index(inplace=True)
pivoted_df.head()

# Sort the columns first by Quantity and then by Row Total, both by MM/YY format
sorted_columns = sorted(pivoted_df.columns, key=lambda x: (x.startswith("Quantity"), x[-7:], x))

# Reorder the DataFrame columns based on the sorted order
pivoted_df = pivoted_df[sorted_columns]

# Print or use the resulting pivoted DataFrame as needed
print(pivoted_df)

csv_file_path = 'MoM_Pivoted.csv'

# Export the DataFrame to a CSV file
pivoted_df.to_csv(csv_file_path, index=False)

# import matplotlib.pyplot as plt

# # Assuming df is your DataFrame with columns "Month," "Item No.," "Quantity," and "Row Total"

# # Specify the Item No. you want to analyze
# item_no_to_analyze = "FGDC0013"  # Replace with your specific Item No.

# # Filter the DataFrame for the specific Item No.
# filtered_df = df[df['Item No.'] == item_no_to_analyze]

# # Group by the "Month" column and sum the "Quantity" or "Row Total"
# grouped_df = filtered_df.groupby('Month')['Quantity'].sum()  # Change to 'Row Total' if needed

# # Create a line plot for month-over-month data
# plt.figure(figsize=(10, 6))
# plt.plot(grouped_df.index, grouped_df.values, marker='o', linestyle='-')
# plt.xlabel('Month')
# plt.ylabel('Total Quantity')  # Change to 'Total Row Total' if needed
# plt.title(f'Month-over-Month Analysis for Item No. {item_no_to_analyze}')
# plt.grid(True)

# # Display the plot
# plt.show()



# df['Posting Date'] = pd.to_datetime(df['Posting Date'], format='%d/%b/%Y')



# df.head()

# # Set the "Posting Date" as the index
# df.set_index('Posting Date', inplace=True)

# # Specify your time frame
# start_date = '2023-08-12'
# end_date = '2023-08-14'

# # Filter the DataFrame based on the time frame
# filtered_df = df[start_date:end_date]

# # Group by "Item no." and calculate the summation of "Row Total"
# result = filtered_df.groupby('Item No.')['Row Total'].sum()

# print(result)

# # Specify your time frame
# start_date = '2023-01-01'
# end_date = '2023-07-31'
# # Filter the DataFrame based on the time frame (including start and end dates)
# filtered_df = df[start_date:end_date]

# # Group by "Item no." and "Item/Service Description", calculate the summation of "Row Total"
# result = filtered_df.groupby(['Item No.', 'Item/Service Description'])['Row Total'].sum()

# # Sort the result in descending order
# result_sorted = result.sort_values(ascending=False)

# print(result_sorted)

# """## Getting top 50 items based on revenue"""

# # Get the top 50 items
# top_10_items = result_sorted.head(50)

# # Format numbers to not use exponential notation
# pd.set_option('display.float_format', '{:.2f}'.format)

# print(top_50_items)

# unique_values = df['Customer/Vendor Name'].unique()

# print(unique_values)

# result = df.to_dict('records')
# result